services:
  postgres:
    image: postgres:12-alpine
    extends:
      file: docker/services/postgres.yml
      service: postgres
  downloader:
    build:
      context: .
      dockerfile: docker/downloader/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "3000:3000"
    command: bash -c 'bundle exec rails db:drop db:create db:schema:load && bundle exec rails db:fixtures:load && bundle exec rails server -b 0.0.0.0'
  rabbitmq:
    extends:
      file: docker/services/rabbitmq.yml
      service: rabbitmq