services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: downloader_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    hostname: postgres
    ports:
      - "5432:5432"
  downloader:
    build:
      context: .
      dockerfile: docker/downloader/Dockerfile-test
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: bash -c 'sleep 10 && bundle exec rails db:drop db:create db:schema:load && bundle exec rails db:fixtures:load && bundle exec rails cucumber'
  rabbitmq:
    build:
      context: .
      dockerfile: ./docker/rabbitmq/Dockerfile-rabbitmq
    hostname: rabbitmq
    ports:
      - "5671:5671"
      - "15672:15672"