services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: downloader_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    hostname: postgres
    ports:
      - "5432:5432"
  downloader:
    build:
      context: .
      dockerfile: docker/downloader/Dockerfile-test
    depends_on:
      - postgres
      - rabbitmq
      - elasticmq
    environment:
      AWS_ACCESS_KEY_ID: dummy_access_key
      AWS_SECRET_ACCESS_KEY: dummy_secret_key
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: bash -c 'sleep 10 && bundle exec rails db:drop db:create db:schema:load && bundle exec rails db:fixtures:load && bundle exec rails cucumber'
  rabbitmq:
    build:
      context: .
      dockerfile: ./docker/rabbitmq/Dockerfile-rabbitmq-test
    hostname: rabbitmq
    ports:
      - "5671:5671"
      - "15672:15672"
  elasticmq:
    image: softwaremill/elasticmq-native:latest
    ports:
      - "9324:9324"  # SQS REST API
      - "9325:9325"  # Optional Web UI
    volumes:
      # Mounts your local config to the expected path inside the container
      - ./docker/elasticMQ/elasticmq.conf:/opt/elasticmq.conf