FROM ubuntu:22.04
FROM ruby:3.2.2

ARG rails_env=test
ENV RAILS_ENV=test
ENV RAILS_LOG_TO_STDOUT=true

RUN apt-get update && apt-get install -y \
    nodejs \
    postgresql-client

EXPOSE 3000

# This is a host volume.
RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN mkdir -p /home/downloader/storage

RUN mkdir -p /home/downloader/mnt/medusa-demo-main-ro
COPY storage/medusa/*  /home/downloader/mnt/medusa-demo-main-ro

RUN mkdir -p /home/downloader/mnt/medusa-demo-main-ro/156/182/
COPY storage/idb/* /home/downloader/mnt/medusa-demo-main-ro/156/182/

RUN mkdir -p /home/downloader/mnt/medusa-demo-main-ro/186/243/
COPY storage/ideals/* /home/downloader/mnt/medusa-demo-main-ro/186/243/

RUN mkdir -p /home/downloader/mnt/medusa-demo-main-ro/test
COPY storage/test/* /home/downloader/mnt/medusa-demo-main-ro/test

RUN mkdir /home/downloader/mnt/medusa-demo-main-ro/test/child

RUN gem install bundler \
    && bundle install

COPY . ./

COPY config/database.yml.test config/database.yml

# Everything else has to be done in the entry command because /app will be
# empty until we launch via docker compose.
