load_module modules/ngx_http_zip_module.so;

worker_processes  auto;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    access_log /logs/nginx_mod_zip_access.log;
    error_log /logs/nginx_mod_zip_error.log debug;

    auth_digest_zone zone=users:1m;

    sendfile        on;

    keepalive_timeout  65;

    upstream rails_app {
        server unix:///var/run/puma.sock fail_timeout=30s;
    }
    server {
        listen       80;
        server_name  localhost;

        location / {
            proxy_pass http://rails_app;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        include /home/nginx/conf/internal.conf;

        location /downloads/create {
            auth_digest "request_creators" zone=users;
            auth_digest_user_file /home/nginx/conf/digest_users;
            proxy_pass http://rails_app/downloads/create;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}