#This file is processed by ERB before being parsed into YAML
admin_email: medusa-notifications@library.illinois.edu
smtp:
  :password: password
s3_common: &S3_COMMON
  :type: s3
  :region: us-east-2
  :aws_access_key_id: access_key
  :aws_secret_access_key: secret_access_key
roots:
  - :name: medusa
    :type: filesystem
    :path: /path/to/medusa
  - :name: idb
    :type: filesystem
    :path: /path/to/idb
  - :name: ideals
    :type: filesystem
    :path: /path/to/ideals
#Note that the storage directory must be able to contain symlinks
storage: /home/downloader/storage
incoming_queue: client_to_downloader
amqp:
  ssl: true
  host: host
  user: downloader
  password: password
  vhost: downloader
  verify_peer: false
#  nginx_url: http://aws-downloader-prod.library.illinois.edu:8080
nginx_url: url
auth:
  realm: request_creators
  active: false
  users:
    idb: password