#This file is processed by ERB before being parsed into YAML
admin_email: medusa-notifications@library.illinois.edu
smtp:
  :password: password
s3_common: &S3_COMMON
  :type: s3
  :region: us-east-2
roots:
  - :name: medusa
    :type: filesystem
    :path: /home/downloader/mnt/medusa-main-ro
  - :name: idb
    :type: filesystem
    :path: /home/downloader/mnt/medusa-main-ro/983/2188
storage: /home/downloader/storage
incoming_queue: client_to_downloader
amqp:
  ssl: true
  host: host
  user: downloader
  password: password
  vhost: downloader
  verify_peer: false
nginx_url: https://download.library.illinois.edu
auth:
  realm: request_creators
  active: false
  users:
    idb: password